title = "Hello™"
slug = "hello"
company_url = "hello.com"
job_board_url = "https://example.com"
body = "example"
country = "germany"
city = "berlin"
updated_at = "2020-12-16"
created_at = "2020-12-16"