stages:
  - trigger-remote-build

variables:
  URL_REMOTE_THEME_REPO: gitlab@job-profile-gatsby:pages

build-remote-site:
  stage: trigger-remote-build
  script:
  - echo "should call remote webhook at $URL_REMOTE_THEME_REPO"
  - echo "done test"
