name: Update existing company
description: Edits that should be made to a project/company already existing on the job list platform
title: "[update] example.org"
labels: ["update-company"]
assignees:
  - user-09876
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to edit the content!

        Do you know that it is actually possible to edit all content directly yourself?! Either:
        - edit the data you wish to change, in the file, on github (and submit a Pull Request)
        - use https://edit.joblist.today with your github account

        If you still have an issue with these methods, continue with this form!

  - type: input
    id: title
    attributes:
      label: Company profile
      description: The URL address to the profile for this company, on the https://profiles.joblist.today platform (use the direct link to the company profile page).
      placeholder: ex. https://profiles.joblist.today/companies/ableton
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The description of your changes/bug for this company.
    validations:
      required: true
