body = "Maker.do is a community and #incubator that help you launching your #startup"
created_at = "2017-06-28T20:30:15.466Z"
is_approved = true
job_board_url = "https://makers-jobs.personio.de/"
latitude = 52.5247523
longitude = 13.4066275
slug = "makersdo"
tags = ["incubator", "startup"]
title = "Makers.do"
updated_at = "2019-06-16T10:36:09.624Z"
draft=true
