title = "Profiles"
contentDir = "."
theme = "companies-theme"
themesDir = ".themes"
baseURL = ""
languageCode = "en-us"


[taxonomies]
tag = "tags"
city = "cities"
position = "positions"

[Params]
editNetlifyCmsUrl = "https://joblist.gitlab.io/cms/#/collections"
featured_taxonomies = ["tags", "cities"]


[menu]
[[menu.main]]
name = "Companies"
url = "/companies"
weight = -110

[[menu.main]]
name = "Tags"
url = "/tags"
weight = -100

# [[menu.main]]
# name = "Cities"
# url = "/cities"
# weight = -90

[[menu.main]]
name = "Positions (map)"
url = "/positions"
weight = -80

[[menu.main]]
name = "Search jobs"
url = "https://joblist.gitlab.io"
weight = -70