title = "Profiles"
contentDir = "."
theme = "companies-theme"
themesDir = ".themes"
baseURL = ""
languageCode = "en-us"

[taxonomies]
tag = "tags"

[Params]
editNetlifyCmsUrl = "https://companies.joblist.city/edit/#/collections"