# labels a newly added issue with the `triage` label

on:
  issues:
    types:
      - opened

jobs:
  label_new_issue:
    runs-on: alpine-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
